export {default as Header} from "./header/Header.jsx";
export {default as Footer} from "./footer/Footer.jsx";
export {default as HeroBanner} from "./home/heroBanner/HeroBanner.jsx";
export {default as Img} from "./lazyLoadImage/Img.jsx";
export {default as ContentWrapper} from "./contentWrapper/ContentWrapper.jsx";
export {default as Trending} from "./home/trending/Trending.jsx";
export {default as SwitchTabs} from "./switchTabs/SwitchTabs.jsx";
export { default as Carousel } from "./carousel/Carousel.jsx";
export { default as CircleRating } from "./CircleRating.jsx";
export { default as Genres } from "./Genres.jsx";
export { default as Popular } from "./home/popular/Popular.jsx";
export { default as DetailsBanner } from "./details/detailsBanner/DetailsBanner.jsx";
export { default as VideoPopup } from "./videoPopup/VideoPopup.jsx";
export { default as Cast } from "./details/cast/Cast.jsx";
export { default as VideosSection } from "./details/videosSection/VideosSection.jsx";
export { default as Similar } from "./details/Similar.jsx";
export { default as Recommendation } from "./details/Recommendation.jsx";
export { default as Spinner } from "./spinner/Spinner.jsx";
export { default as MovieCard } from "./movieCard/MovieCard.jsx";
